### ISSUE TITLE
Introduce a cookbook section in the documentation site

### ISSUE THREAD

**Issue by customcommander** [customcommander/functionaut#37]
The library aims to offer a set of functions to promote a development style that favours currying, partial application and composition. So care must be taken that we do not introduce specialised functions as the goal is not to become a toolkit such as Underscore or Lodash.

However it would be useful to show people how such functions can be designed.

**Tasks**

- [ ] Create a "Cookbook" top navigation
- [ ] Cookbook should be a single page with a ToC
- [ ] First recipe could be `range`; see #5 
- [ ] The cookbook should be built from code instead of manually put together

In order to make sure that recipes are still working, the cookbook should be built from code. It could be a single test file that is then parsed to extract symbols, descriptions and examples.
